.TH "DH_SUBST" "1" "2011-12-09"
.ad l
.nh
.SH "NAME"
dh_subst \- Debhelper executable file substition helpers
.SH "SYNOPSIS"
\fB#! /usr/bin/dh_subst\fR
.br
src/libfoo-p.so.* debian/libfoo-p/usr/lib/libfoo/${DEB_HOST_MULTIARCH}/

.SH "DESCRIPTION"
dh_subst is a simple program, meant to be used as the interpreter for
executable debhelper config files.

It is a wrapper around the various other substitution helpers, and
will pipe the input file through all the available substitution
helpers. It is up to these scripts to do the actual work.

When a helper fails to expand a variable within its input, it will
leave it as-is, so that later in the pipeline it can perhaps be
expanded by another program.

.SH "HELPERS"

.TP
.B dh_subst_env
Substitutes any of the available, exported environment variables into
its input. It does not do any kind of filtering: whatever is available
in the environment, will be available for substitution, however unsafe
that may be.

.SH "ENVIRONMENT"
.PP
\fIDH_SUBST_LIBDIR\fR
.RS 4
Indicates which directory the substitution helpers should be sought
for. If not specified, helpers will be searched for in
\fI/usr/lib/dh-subst/\fR.
.RE

.SH "FILES"
.PP
\fI$DH_SUBST_LIBDIR/dh_subst_*\fR
.RS 4
The various substitution helpers.
.RE

.SH "SEE ALSO"
debhelper(1)

.SH "AUTHOR"
dh_subst is copyright \(c 2011 by Gergely Nagy <algernon@madhouse\-project.org>.
