#! /bin/sh
## This part of the magic was borrowed from Goswin von Brederlow
## <goswin-v-b@web.de>, from a post of his to debian-devel@.
##
## The purpose of the script is to copy all files that need a rename,
## and echo back the original contents for all files that do not need
## one (ie, the destination ends with /).
##
## As a special case, if a source file is not found, it will be
## checked under debian/tmp too.

while read SRC DEST; do
        case "${SRC}" in
                (\#*|"")
                        continue
                        ;;
        esac
        case "${DEST}" in
                (*/)
                        ;;
                (*)
                        if [ ! -e "${SRC}" ] && [ -e "debian/tmp/${SRC}" ]; then
                                SRC="debian/tmp/${SRC}"
                        fi
                        PKG=$(basename -- "${DH_EXEC_SOURCE}" ".install")
                        cp -- "${SRC}" "debian/${PKG}/${DEST}"
                        continue
                        ;;
                
        esac;
        printf -- "%s %s\n" "${SRC}" "${DEST}"
done
