#! /usr/bin/perl -wnp
##
## Akin to dh_subst_env, this one will try to expand variables within
## its input, but only certain ones, and will fall back to querying
## dpkg-architecture first, before finally giving up.
$_ = "" if /^#/;
s#(\$\{(DEB_(HOST|BUILD)_[^\}]+)\})#`dpkg-architecture -q$2 2>/dev/null | tr -d "\n"` || $1#eg;
