#! /bin/sh

set -e

. ${srcdir}/test.lib.sh

tl_plan 1

# The she-bang gets removed from the output
(cat <<EOF
#! ${top_builddir}/src/dh-exec-subst
# This is another comment.
we add some stuff, such as \${DH_EXEC_SOURCE}

# and some more comments
and in the end, we quit
EOF
) | ${top_builddir}/src/dh-exec-subst | \
        tl_forbid "Comments get removed" "#"
tl_next
