#! /bin/sh

. ${srcdir}/test.lib.sh

tl_plan 5

# Calling as a she-bang works
t=$(mktemp --tmpdir=. tmpXXXXXXXX.install)
td=$(mktemp -d --tmpdir=. tmpXXXXX)
dd="debian/$(basename -- ${t} .install)"

install -d "${dd}/var/lib/dh-exec"

cat >"${t}" <<EOF
#! ${top_builddir}/src/dh-exec-install
$(basename ${t}) /var/lib/dh-exec/test-output
# This is an empty line:


EOF

chmod +x "${t}"
"${t}" | tl_forbid "Calling as a she-bang works" "test-output"
tl_next

# ...and it even copies the file
find "${dd}" -name 'test-output' | \
        tl_expect_match "Copying did happen" "test-output"
rm -f "${t}"
rm -rf "${td}" "${dd}"

tl_next

# Check copying without rename
t=$(mktemp --tmpdir tmpXXXXXX.install)
td=$(mktemp --tmpdir -d tmpXXXXXX)

cat >"${t}" <<EOF
#! ${top_builddir}/src/dh-exec-install
$(basename ${t})* /var/lib/dh-exec/
EOF

chmod +x "${t}"
"${t}" | tl_expect_match "Copying to a dir should echo the contents back" \
                         "/var/lib/dh-exec"
rm -f "${t}"
rm -rf "${td}"
tl_next

# Check copying from debian/tmp
t=$(mktemp --tmpdir tmpXXXXXXXX.install)
td=$(mktemp --tmpdir -d tmpXXXXX)
dd="debian/$(basename -- ${t} .install)"

install -d "debian/tmp"
install -d "${dd}/var/lib/dh-exec"

echo "foobar" >"debian/tmp/foo.test"

cat >"${t}" <<EOF
#! ${top_builddir}/src/dh-exec-install
foo.test /var/lib/dh-exec/test-output
EOF

chmod +x "${t}"
"${t}" | tl_forbid "Copying from debian/tmp works" "test-output"
tl_next

# ...and it even copies the file
cat "${dd}/var/lib/dh-exec/test-output" | tl_expect "Copying did happen" "foobar"
rm -f "${t}"
rm -rf "${td}" "${dd}" "debian/"

tl_next
