#! /bin/sh

set -e

. ${srcdir}/test.lib.sh

case $(dpkg-query -f '${Version}' --show debhelper) in
        9*)
                ;;
        *)
                tl_plan "0 # SKIP: Debhelper too old"
                exit 0
                ;;
esac

tl_plan 24

cd ${DH_EXEC_BINDIR}
BINDIR=$(pwd)
cd - >/dev/null

cd ${DH_EXEC_SCRIPTDIR}
SCRIPTDIR=$(pwd)
cd - >/dev/null

cd ${DH_EXEC_LIBDIR}
LIBDIR=$(pwd)
cd - >/dev/null

td=$(mktemp -d --tmpdir=. tmpXXXXXX)
tar -C ${srcdir} -c pkg-test | tar -C ${td} -x

chmod -R ugo+rX,u+w ${td}
cd ${td}/pkg-test

check_pkg () {
        arch=${1:+-a$1}

        ln -sf ${BINDIR}/dh-exec .
        
        DEB_HOST_MULTIARCH=$(dpkg-architecture ${arch} -f -qDEB_HOST_MULTIARCH 2>/dev/null)

        PATH=${BINDIR}:${PATH} DH_EXEC_SCRIPTDIR=${SCRIPTDIR} DH_EXEC_LIBDIR=${LIBDIR} \
                dpkg-buildpackage -us -uc -b -d ${arch} 2>/dev/null
        debian/rules clean
        rm -f dh-exec

        dpkg-deb -c ../pkg-test_0_all.deb | \
                tl_expect_match "usr/bin/bin-foo installed" "./usr/bin/bin-foo"
        tl_next
        dpkg-deb -c ../pkg-test_0_all.deb | \
                tl_expect_match "usr/bin/bin-arch installed" "./usr/bin/bin-arch"
        tl_next
        dpkg-deb -c ../pkg-test_0_all.deb | \
                tl_expect_match "multi-arch path works" "./usr/lib/pkg-test/${DEB_HOST_MULTIARCH}/plugin-multiarch"
        tl_next
        dpkg-deb -c ../pkg-test_0_all.deb | \
                tl_expect_match "multi-arch path works" "./usr/lib/pkg-test/${DEB_HOST_MULTIARCH}/another-plugin\$"
        tl_next

        dpkg-deb -c ../pkg-test-illiterate_0_all.deb | \
                tl_expect_match "usr/bin/bin-foo installed" "./usr/bin/bin-foo"
        tl_next
        dpkg-deb -c ../pkg-test-illiterate_0_all.deb | \
                tl_expect_match "usr/bin/bin-arch installed" "./usr/bin/bin-arch"
        tl_next
        dpkg-deb -c ../pkg-test-illiterate_0_all.deb | \
                tl_expect_match "multi-arch path works" "./usr/lib/pkg-test/${DEB_HOST_MULTIARCH}/plugin-multiarch"
        tl_next
        dpkg-deb -c ../pkg-test-illiterate_0_all.deb | \
                tl_expect_match "multi-arch path works" "./usr/lib/pkg-test/${DEB_HOST_MULTIARCH}/another-plugin\$"
        tl_next
}

check_pkg
check_pkg linux-powerpc
check_pkg kfreebsd-i386

cd ../..
rm -rf ${td}
